//
//  Capitals.swift
//  GuessTheFlag
//
//  Created by Vladimir Kolev on 07.02.25.
//

struct Country {
    let name: String
    let capital: String
}

let CAPITALS = [
    Country(name: "Andorra", capital: "Andorra la Vella"),
    Country(name: "United Arab Emirates", capital: "Abu Dhabi"),
    Country(name: "Afghanistan", capital: "Kabul"),
    Country(name: "Antigua and Barbuda", capital: "Saint John's"),
    Country(name: "Albania", capital: "Tirana"),
    Country(name: "Armenia", capital: "Yerevan"),
    Country(name: "Angola", capital: "Luanda"),
    Country(name: "Argentina", capital: "Buenos Aires"),
    Country(name: "Austria", capital: "Vienna"),
    Country(name: "Australia", capital: "Canberra"),
    Country(name: "Azerbaijan", capital: "Baku"),
    Country(name: "Bosnia and Herzegovina", capital: "Sarajevo"),
    Country(name: "Barbados", capital: "Bridgetown"),
    Country(name: "Bangladesh", capital: "Dhaka"),
    Country(name: "Belgium", capital: "Brussels"),
    Country(name: "Burkina Faso", capital: "Ouagadougou"),
    Country(name: "Bulgaria", capital: "Sofia"),
    Country(name: "Bahrain", capital: "Manama"),
    Country(name: "Burundi", capital: "Gitega"),
    Country(name: "Benin", capital: "Porto-Novo"),
    Country(name: "Brunei Darussalam", capital: "Bandar Seri Begawan"),
    Country(name: "Bolivia, Plurinational State of", capital: "Sucre"),
    Country(name: "Brazil", capital: "Brasília "),
    Country(name: "Bahamas", capital: "Nassau"),
    Country(name: "Bhutan", capital: "Thimphu"),
    Country(name: "Botswana", capital: "Gaborone"),
    Country(name: "Belarus", capital: "Minsk"),
    Country(name: "Belize", capital: "Belmopan"),
    Country(name: "Canada", capital: "Ottawa"),
    Country(name: "Congo, the Democratic Republic of the", capital: "Kinshasa"),
    Country(name: "Central African Republic", capital: "Bangui"),
    Country(name: "Republic of the Congo", capital: "Brazzaville"),
    Country(name: "Switzerland", capital: "Bern"),
    Country(name: "Côte d'Ivoire", capital: "Yamoussoukro"),
    Country(name: "Chile", capital: "Santiago"),
    Country(name: "Cameroon", capital: "Yaoundé"),
    Country(name: "Colombia", capital: "Bogotá"),
    Country(name: "Costa Rica", capital: "San José"),
    Country(name: "Cuba", capital: "Havana"),
    Country(name: "Curaçao", capital: "Amsterdam"),
    Country(name: "Cyprus", capital: "Nicosia"),
    Country(name: "Czech Republic", capital: "Prague"),
    Country(name: "Germany", capital: "Berlin"),
    Country(name: "Djibouti", capital: "Djibouti"),
    Country(name: "Denmark", capital: "Copenhagen"),
    Country(name: "Dominica", capital: "Roseau"),
    Country(name: "Dominican Republic", capital: "Santo Domingo"),
    Country(name: "Algeria", capital: "Algiers"),
    Country(name: "Ecuador", capital: "Quito"),
    Country(name: "Estonia", capital: "Tallinn"),
    Country(name: "Egypt", capital: "Cairo"),
    Country(name: "Eritrea", capital: "Asmara"),
    Country(name: "Spain", capital: "Madrid"),
    Country(name: "Ethiopia", capital: "Addis Ababa"),
    Country(name: "Finland", capital: "Helsinki"),
    Country(name: "Fiji", capital: "Suva"),
    Country(name: "Micronesia, Federated States of", capital: "Palikir"),
    Country(name: "France", capital: "Paris"),
    Country(name: "Gabon", capital: "Libreville"),
    Country(name: "England", capital: "London"),
    Country(name: "Northern Ireland", capital: "London"),
    Country(name: "Scotland", capital: "London"),
    Country(name: "Wales", capital: "London"),
    Country(name: "United Kingdom", capital: "London"),
    Country(name: "Grenada", capital: "St. George's"),
    Country(name: "Georgia", capital: "Tbilisi"),
    Country(name: "Ghana", capital: "Accra"),
    Country(name: "Gambia", capital: "Banjul"),
    Country(name: "Guinea", capital: "Conakry"),
    Country(name: "Equatorial Guinea", capital: "Malabo"),
    Country(name: "Greece", capital: "Athens"),
    Country(name: "Guatemala", capital: "Guatemala City"),
    Country(name: "Guinea-Bissau", capital: "Bissau"),
    Country(name: "Guyana", capital: "Georgetown"),
    Country(name: "Honduras", capital: "Tegucigalpa"),
    Country(name: "Croatia", capital: "Zagreb"),
    Country(name: "Haiti", capital: "Port-au-Prince"),
    Country(name: "Hungary", capital: "Budapest"),
    Country(name: "Indonesia", capital: "Jakarta"),
    Country(name: "Ireland", capital: "Dublin"),
    Country(name: "Israel", capital: "Jerusalem"),
    Country(name: "India", capital: "New Delhi"),
    Country(name: "Iraq", capital: "Baghdad"),
    Country(name: "Iran, Islamic Republic of", capital: "Tehran"),
    Country(name: "Iceland", capital: "Reykjavik"),
    Country(name: "Italy", capital: "Rome"),
    Country(name: "Jamaica", capital: "Kingston"),
    Country(name: "Jordan", capital: "Amman"),
    Country(name: "Japan", capital: "Tokyo"),
    Country(name: "Kenya", capital: "Nairobi"),
    Country(name: "Kyrgyzstan", capital: "Bishkek"),
    Country(name: "Cambodia", capital: "Phnom Penh"),
    Country(name: "Kiribati", capital: "South Tarawa"),
    Country(name: "Comoros", capital: "Moroni"),
    Country(name: "Saint Kitts and Nevis", capital: "Basseterre"),
    Country(name: "Korea, Democratic People's Republic of", capital: "Pyongyang"),
    Country(name: "Korea, Republic of", capital: "Seoul"),
    Country(name: "Kuwait", capital: "Kuwait City"),
    Country(name: "Kazakhstan", capital: "Nur-Sultan"),
    Country(name: "Lebanon", capital: "Beirut"),
    Country(name: "Saint Lucia", capital: "Castries"),
    Country(name: "Liechtenstein", capital: "Vaduz"),
    Country(name: "Sri Lanka", capital: "Sri Jayawardenepura Kotte"),
    Country(name: "Liberia", capital: "Monrovia"),
    Country(name: "Lesotho", capital: "Maseru"),
    Country(name: "Lithuania", capital: "Vilnius"),
    Country(name: "Luxembourg", capital: "Luxembourg"),
    Country(name: "Latvia", capital: "Riga"),
    Country(name: "Libya", capital: "Tripoli"),
    Country(name: "Morocco", capital: "Rabat"),
    Country(name: "Monaco", capital: "Monaco"),
    Country(name: "Moldova, Republic of", capital: "Chișinău"),
    Country(name: "Montenegro", capital: "Podgorica"),
    Country(name: "Madagascar", capital: "Antananarivo"),
    Country(name: "Marshall Islands", capital: "Majuro"),
    Country(name: "North Macedonia", capital: "Skopje"),
    Country(name: "Mali", capital: "Bamako"),
    Country(name: "Myanmar", capital: "Naypyidaw"),
    Country(name: "Mongolia", capital: "Ulan Bator"),
    Country(name: "Mauritania", capital: "Nouakchott"),
    Country(name: "Malta", capital: "Valletta"),
    Country(name: "Mauritius", capital: "Port Louis"),
    Country(name: "Maldives", capital: "Malé"),
    Country(name: "Malawi", capital: "Lilongwe"),
    Country(name: "Mexico", capital: "Mexico City"),
    Country(name: "Malaysia", capital: "Kuala Lumpur"),
    Country(name: "Mozambique", capital: "Maputo"),
    Country(name: "Namibia", capital: "Windhoek"),
    Country(name: "Niger", capital: "Niamey"),
    Country(name: "Nigeria", capital: "Abuja"),
    Country(name: "Nicaragua", capital: "Managua"),
    Country(name: "Netherlands", capital: "Amsterdam"),
    Country(name: "Norway", capital: "Oslo"),
    Country(name: "Nepal", capital: "Kathmandu"),
    Country(name: "Nauru", capital: "Yaren"),
    Country(name: "New Zealand", capital: "Wellington"),
    Country(name: "Oman", capital: "Muscat"),
    Country(name: "Panama", capital: "Panama City"),
    Country(name: "Peru", capital: "Lima"),
    Country(name: "Papua New Guinea", capital: "Port Moresby"),
    Country(name: "Philippines", capital: "Manila"),
    Country(name: "Pakistan", capital: "Islamabad"),
    Country(name: "Poland", capital: "Warsaw"),
    Country(name: "Portugal", capital: "Lisbon"),
    Country(name: "Palau", capital: "Ngerulmud"),
    Country(name: "Paraguay", capital: "Asunción"),
    Country(name: "Qatar", capital: "Doha"),
    Country(name: "Romania", capital: "Bucharest"),
    Country(name: "Serbia", capital: "Belgrade"),
    Country(name: "Russian Federation", capital: "Moscow"),
    Country(name: "Rwanda", capital: "Kigali"),
    Country(name: "Saudi Arabia", capital: "Riyadh"),
    Country(name: "Solomon Islands", capital: "Honiara"),
    Country(name: "Seychelles", capital: "Victoria"),
    Country(name: "Sudan", capital: "Khartoum"),
    Country(name: "Sweden", capital: "Stockholm"),
    Country(name: "Singapore", capital: "Singapore"),
    Country(name: "Slovenia", capital: "Ljubljana"),
    Country(name: "Slovakia", capital: "Bratislava"),
    Country(name: "Sierra Leone", capital: "Freetown"),
    Country(name: "San Marino", capital: "City of San Marino"),
    Country(name: "Senegal", capital: "Dakar"),
    Country(name: "Somalia", capital: "Mogadishu"),
    Country(name: "Suriname", capital: "Paramaribo"),
    Country(name: "South Sudan", capital: "Juba"),
    Country(name: "Sao Tome and Principe", capital: "São Tomé"),
    Country(name: "El Salvador", capital: "San Salvador"),
    Country(name: "Syrian Arab Republic", capital: "Damascus"),
    Country(name: "Kingdom of Eswatini", capital: "Mbabane"),
    Country(name: "Chad", capital: "N'Djamena"),
    Country(name: "Togo", capital: "Lomé"),
    Country(name: "Thailand", capital: "Bangkok"),
    Country(name: "Tajikistan", capital: "Dushanbe"),
    Country(name: "Timor-Leste", capital: "Dili"),
    Country(name: "Turkmenistan", capital: "Ashgabat"),
    Country(name: "Tunisia", capital: "Tunis"),
    Country(name: "Tonga", capital: "Nuku'alofa"),
    Country(name: "Republic of Türkiye", capital: "Ankara"),
    Country(name: "Trinidad and Tobago", capital: "Port of Spain"),
    Country(name: "Tuvalu", capital: "Funafuti"),
    Country(name: "Tanzania, United Republic of", capital: "Dodoma"),
    Country(name: "Ukraine", capital: "Kyiv"),
    Country(name: "Uganda", capital: "Kampala"),
    Country(name: "United States", capital: "Washington, D.C."),
    Country(name: "Uruguay", capital: "Montevideo"),
    Country(name: "Uzbekistan", capital: "Tashkent"),
    Country(name: "Saint Vincent and the Grenadines", capital: "Kingstown"),
    Country(name: "Venezuela, Bolivarian Republic of", capital: "Caracas"),
    Country(name: "Vietnam", capital: "Hanoi"),
    Country(name: "Vanuatu", capital: "Port Vila"),
    Country(name: "Samoa", capital: "Apia"),
    Country(name: "Kosovo", capital: "Belgrade"),
    Country(name: "Yemen", capital: "Sana'a"),
    Country(name: "South Africa", capital: "Pretoria"),
    Country(name: "Zambia", capital: "Lusaka"),
    Country(name: "Zimbabwe", capital: "Harare"),
]
